const fs = require('node:fs');
const path = require('node:path');
const { buildCapabilityReport } = require('../src/capability-registry.cjs');
const root = path.join(__dirname, '..');
const version = require('../package.json').version;

function markdown(report) {
  const lines = [
    '# Poolside capability report',
    '',
    '<!-- Generated by scripts/product-truth.cjs. Edit src/capability-registry.cjs instead. -->',
    '',
    '<!-- prettier-ignore-start -->',
    `Build: ${report.version} (${report.channel}). This is a development preview, not a production qualification.`,
    '',
    '| Capability | Mode | Validation | Flag | Boundary |',
    '| --- | --- | --- | --- | --- |'
  ];
  for (const item of report.capabilities) {
    lines.push(`| ${item.name} | ${item.mode} | ${item.validation} | ${item.flag} | ${item.detail} |`);
  }
  lines.push('', '## Support boundary', '');
  for (const [key, value] of Object.entries(report.support)) lines.push(`- ${key}: ${value}`);
  lines.push('', 'Validation levels do not imply real-game accuracy, authentication, legal approval, or signed-release readiness.', '<!-- prettier-ignore-end -->', '');
  return lines.join('\n');
}

function expectedFiles() {
  const report = buildCapabilityReport(version);
  return new Map([
    [path.join(root, 'docs', 'CAPABILITIES.md'), markdown(report)],
    [path.join(root, 'docs', 'capabilities.json'), JSON.stringify(report, null, 2) + '\n']
  ]);
}

function run(write = false) {
  let stale = 0;
  for (const [file, expected] of expectedFiles()) {
    if (write) fs.writeFileSync(file, expected);
    else if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n') !== expected) {
      console.error(`Stale product truth: ${path.relative(root, file)}`);
      stale++;
    }
  }
  if (stale) process.exitCode = 1;
}

if (require.main === module) run(process.argv.includes('--write'));
module.exports = { markdown, expectedFiles, run };
