const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('poolside', {
  get: () => ipcRenderer.invoke('workspace:get'),
  addRoutePreset: input => ipcRenderer.invoke('route-preset:add', input),
  deleteRoutePreset: id => ipcRenderer.invoke('route-preset:delete', id),
  add: input => ipcRenderer.invoke('account:add', input),
  open: id => ipcRenderer.invoke('account:open', id),
  close: id => ipcRenderer.invoke('account:close', id),
  checkIP: id => ipcRenderer.invoke('account:check-ip', id),
  checkRoute: id => ipcRenderer.invoke('account:check-route', id),
  deleteProfile: id => ipcRenderer.invoke('account:delete-profile', id),
  refreshProfiles: () => ipcRenderer.invoke('profiles:refresh'),
  settingsForm: () => ipcRenderer.invoke('settings:form'),
  diagnosticsPreview: () => ipcRenderer.invoke('diagnostics:preview'),
  diagnosticsSave: () => ipcRenderer.invoke('diagnostics:save'),
  diagnosticsOpenFolder: () => ipcRenderer.invoke('diagnostics:open-folder'),
  backupExport: () => ipcRenderer.invoke('backup:export'),
  backupImport: () => ipcRenderer.invoke('backup:import'),
  clearActivityHistory: () => ipcRenderer.invoke('activity:history-clear'),
  returnGame: id => ipcRenderer.invoke('account:return-game', id),
  reload: id => ipcRenderer.invoke('account:reload', id),
  inspect: id => ipcRenderer.invoke('account:inspect', id),
  startTableNavigation: input => ipcRenderer.invoke('table-navigation:start', input),
  observeTableNavigation: id => ipcRenderer.invoke('table-navigation:observe', id),
  advanceTableNavigation: id => ipcRenderer.invoke('table-navigation:advance', id),
  cancelTableNavigation: id => ipcRenderer.invoke('table-navigation:cancel', id),
  retryTableNavigation: id => ipcRenderer.invoke('table-navigation:retry', id),
  startMonitor: id => ipcRenderer.invoke('account:monitor-start', id),
  stopMonitor: id => ipcRenderer.invoke('account:monitor-stop', id),
  captureList: () => ipcRenderer.invoke('capture:list'),
  captureRecord: input => ipcRenderer.invoke('capture:record', input),
  captureImage: id => ipcRenderer.invoke('capture:image', id),
  captureDelete: id => ipcRenderer.invoke('capture:delete', id),
  captureReview: id => ipcRenderer.invoke('capture:review', id),
  captureSetCohort: input => ipcRenderer.invoke('capture:set-cohort', input),
  archive: id => ipcRenderer.invoke('account:archive', id),
  bulk: input => ipcRenderer.invoke('account:bulk', input),
  restore: id => ipcRenderer.invoke('account:restore', id),
  update: input => ipcRenderer.invoke('account:update', input),
  accountPreferencesForm: id => ipcRenderer.invoke('account:preferences-form', id),
  saveAccountPreferences: input => ipcRenderer.invoke('account:preferences-save', input),
  deleteAccount: id => ipcRenderer.invoke('account:delete', id),
  openAll: () => ipcRenderer.invoke('sessions:open'),
  closeAll: () => ipcRenderer.invoke('sessions:close'),
  arrange: () => ipcRenderer.invoke('sessions:arrange'),
  saveSettings: input => ipcRenderer.invoke('settings:save', input),
  subscribe: listener => {
    const handler = (_event, value) => listener(value);
    ipcRenderer.on('workspace:changed', handler);
    return () => ipcRenderer.removeListener('workspace:changed', handler);
  }
});
